#########################################################################
####                         公共基础配置                              ####
#########################################################################
server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: prod
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
    proxy-target-class: true


#########################################################################
####                     mybatis plus 配置                            ####
#########################################################################
mybatis-plus:
  # 实体类扫描路径
  type-aliases-package: com.geekerstar.*.entity
  # xml 扫描路径
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false
    db-config:
      select-strategy: not_empty
# Mybatis 输出sql日志
logging:
  level:
    com.hantu.mapper: debug
